=== SaturnCassini/fortune-contracts/venv/lib/python3.8/site-packages/mythx_models/response/schema/detected-issues.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "issues",
            "sourceType",
            "sourceFormat",
            "sourceList",
            "meta"
        ],
        "properties": {
            "issues": {
                "type": "array",
                "items": {
                    "type": "object",
                    "required": [
                        "swcID",
                        "swcTitle",
                        "description",
                        "severity",
                        "locations",
                        "extra"
                    ],
                    "properties": {
                        "decodedLocations": {
                            "type": [
                                "null",
                                "array"
                            ],
                            "items": {
                                "type": "array",
                                "items": {
                                    "anyOf": [
                                        {
                                            "type": "boolean"
                                        },
                                        {
                                            "type": "object",
                                            "required": [
                                                "column",
                                                "line"
                                            ],
                                            "properties": {
                                                "column": {
                                                    "type": "integer"
                                                },
                                                "line": {
                                                    "type": "integer"
                                                }
                                            }
                                        }
                                    ]
                                }
                            }
                        },
                        "swcID": {
                            "type": "string",
                            "default": ""
                        },
                        "swcTitle": {
                            "type": "string"
                        },
                        "description": {
                            "type": "object",
                            "required": [
                                "head",
                                "tail"
                            ],
                            "properties": {
                                "head": {
                                    "type": "string"
                                },
                                "tail": {
                                    "type": "string"
                                }
                            }
                        },
                        "severity": {
                            "type": [
                                "string",
                                "null"
                            ]
                        },
                        "locations": {
                            "type": [
                                "array",
                                "null"
                            ],
                            "items": {
                                "type": "object",
                                "properties": {
                                    "sourceMap": {
                                        "type": [
                                            "string",
                                            "null"
                                        ]
                                    },
                                    "sourceType": {
                                        "type": [
                                            "string",
                                            "null"
                                        ]
                                    },
                                    "sourceFormat": {
                                        "type": [
                                            "string",
                                            "null"
                                        ]
                                    },
                                    "sourceList": {
                                        "type": [
                                            "array",
                                            "null"
                                        ],
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        },
                        "extra": {
                            "type": "object"
                        }
                    }
                }
            },
            "sourceType": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "sourceFormat": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "sourceList": {
                "type": [
                    "array",
                    "null"
                ],
                "items": {
                    "type": "string"
                }
            },
            "meta": {
                "type": "object"
            }
        }
    },
    "definitions": {
        "issue": {
            "type": "object",
            "required": [
                "swcID",
                "swcTitle",
                "description",
                "severity",
                "locations",
                "extra"
            ],
            "properties": {
                "swcID": {
                    "type": [
                        "null",
                        "string"
                    ],
                    "default": ""
                },
                "swcTitle": {
                    "type": [
                        "null",
                        "string"
                    ]
                },
                "description": {
                    "type": [
                        "null",
                        "object"
                    ],
                    "required": [
                        "head",
                        "tail"
                    ],
                    "properties": {
                        "head": {
                            "type": "string"
                        },
                        "tail": {
                            "type": "string"
                        }
                    }
                },
                "severity": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "locations": {
                    "type": [
                        "array",
                        "null"
                    ],
                    "items": {
                        "type": "object",
                        "properties": {
                            "sourceMap": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "sourceType": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "sourceFormat": {
                                "type": [
                                    "string",
                                    "null"
                                ]
                            },
                            "sourceList": {
                                "type": [
                                    "array",
                                    "null"
                                ],
                                "items": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "extra": {
                    "type": "object"
                }
            }
        }
    }
}

=== SaturnCassini/fortune-contracts/venv/lib/python3.8/site-packages/tests/testdata/detected-issues-response.json
[
    {
        "issues": [
            {
                "swcID": "SWC-103",
                "swcTitle": "Floating Pragma",
                "description": {
                    "head": "A floating pragma is set.",
                    "tail": "It is recommended to make a conscious choice on what version of Solidity is used for compilation. Currently any version equal or greater than \\\"0.4.24\\\" is allowed."
                },
                "severity": "Low",
                "locations": [
                    {
                        "sourceMap": "25:75:0:-;;;59:38;;;;;;;;;94:1;86:10;;59:38;;;;;;;;;;;:::i;:::-;;25:75;8:9:-1;5:2;;;30:1;27;20:12;5:2;25:75:0;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::i;:::-;;;:::o;:::-;;;;;;;;;;;;;;;;;;;;;;;;;;;:::o;:::-;;;;;;;",
                        "sourceType": "raw-bytecode",
                        "sourceFormat": "evm-byzantium-bytecode",
                        "sourceList": [
                            "PublicStorageArray.sol"
                        ]
                    }
                ],
                "extra": {},
                "decodedLocations": [
                    [
                        {
                            "line": 1,
                            "column": 2
                        },
                        {
                            "line": 3,
                            "column": 4
                        },
                        false
                    ]
                ]
            }
        ],
        "sourceType": "raw-bytecode",
        "sourceFormat": "evm-byzantium-bytecode",
        "sourceList": [
            "PublicStorageArray.sol"
        ],
        "meta": {}
    }
]
